services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: kaitou-app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pnpm", "run", "start"]

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    container_name: kaitou-app-tunnel
    command: ["tunnel", "--no-autoupdate", "run"]
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
